(defvar /alchemie_bag /bag "alchemie bag")
(defun /alchemie_loot (item)                     "loot alchemie ingredience"
  (/send (concat "get " item))
  (if (string= /alchemie_bag "belt")
      (/queue "remove belt"
	      (concat "put " item " belt")
	      "wear belt")
    (/queue (concat "put " item " " /alchemie_bag))
    )
  )

(defun /gather-alchemie () "gather alchemie"
  (/trigger "The fang of a white wolf is lying here." '/alchemie_loot "fang")
  (/trigger "A raw diamond is lying here." '/alchemie_loot "diamond")
  (/trigger "A lizard has lost his tail here." '/alchemie_loot "lizard")
  (/trigger "The claw of a bear is lying here." '/alchemie_loot "bear")
  (/trigger "A bundle of valerin is growing here." '/alchemie_loot "valerin")
  (/trigger "A tentacle of an octopus is floating here." '/alchemie_loot "octopus")
  (/trigger "Some pine cones are lying here." '/alchemie_loot "pine")
  (/trigger "The feather of an eagle has fallen to the ground." '/alchemie_loot "feather")
  (/trigger "A mossy twig is lying here on the ground." '/alchemie_loot "mossy")
  (/trigger "A bunch of sage is lying here." '/alchemie_loot "sage")
  (/trigger "You see a bit of ice-covered grass in the snow." '/alchemie_loot "grass")
  (/trigger "Some algae are floating around here." '/alchemie_loot "algae")
  (/trigger "The bones of a fish are floating on the water here." '/alchemie_loot "bones")
  (/trigger "A palm tree's leaf has been carried here by the wind." '/alchemie_loot "leaf")
  (/trigger "A bit of kelp is here." '/alchemie_loot "kelp")
  (/trigger "A blistered rock is lying in the sand." '/alchemie_loot "blistered")
  (/trigger "A pile of snow is here." '/alchemie_loot "snow")
  (/trigger "You see some frozen lichens." '/alchemie_loot "lichens")
  (/trigger "A toadstool is lying here." '/alchemie_loot "toadstool")
  (/trigger "The tail of a mouse is lying here." '/alchemie_loot "tail")
  (/trigger "A sand dollar is floating around." '/alchemie_loot "sand")
  (/trigger "A snow-covered rock is lying on the cold ground." '/alchemie_loot "rock")
  (/trigger "A piece of driftwood is drifting along the water." '/alchemie_loot "driftwood")
  (/trigger "The beard of a goat is lying here." '/alchemie_loot "goat")
  (/trigger "A small cactus has grown here." '/alchemie_loot "cactus")
  (/trigger "The pinchers of a scorpion are lying in the sand." '/alchemie_loot "scorpion")
  (/trigger "An icicle is lying around here." '/alchemie_loot "icicle")
  (/trigger "Some frosty leaves are lying here." '/alchemie_loot "leaves")
  (/trigger "Some black sand is here." '/alchemie_loot "sand")
  (/trigger "A bunch of seaweed is swimming here." '/alchemie_loot "seaweed")
  (/trigger "A piece of quartz is lying here." '/alchemie_loot "quartz")
  (/trigger "A twig, withered by the dryness, is sticking out of the sand." '/alchemie_loot "twig")
  (/trigger "The beak of a penguin is lying here." '/alchemie_loot "beak")
  (/trigger "A lump of coal is lying here." '/alchemie_loot "coal")
  (/trigger "The ear of a seal is lying in the snow." '/alchemie_loot "seal")
  (/trigger "You see some tumbleweed sticking out of the sand." '/alchemie_loot "tumbleweed")
  (/trigger "The fin of a shark is swimming lifelessly on the water." '/alchemie_loot "fin")
  (/trigger "A beautiful seashell is floating around." '/alchemie_loot "seashell")
  (/trigger "A piece of bark is lying here." '/alchemie_loot "bark")
  (/trigger "Some nettles are lying here." '/alchemie_loot "nettles")
  (/trigger "A few brambles are growing here." '/alchemie_loot "brambles")
  (/trigger "The eye of a newt is lying here." '/alchemie_loot "eye")
  (/trigger "Some elderberries are growing here." '/alchemie_loot "elderberries")
  (/trigger "A dragon has lost one of his scales here." '/alchemie_loot "dragon")
  (/trigger "The leg of a spider is lying in the sand." '/alchemie_loot "leg")
)