(/load "emuds-dopath")

(setq emuds-rooms
      (list
       '("alkhan" "The Temple of Al'khandriis")
       '("dokhan" "Boarding Platform")
       '("moonglow" "The Great Temple of Moonglow")
       '("alisia" "A Road in the Dense Forest")
       '("mitra" "Inside the Temple of Mitra")
       '("atalia" "Atalian Temple")
       '("saru" "The Shrine of Ryuginko")
       '("riva" "The Temple of Riva")
       '("fanhir" "The Temple of the Sea-Devils")
       '("black_harbour" "The Black Harbour")
       '("kerofk" "Temple of Bhao")
       '("rand" "In a Clearing")
       '("demonlord" "Summoning Room")
       '("weramak" "Before the great Gate of Weramak")
       '("ofcol" "The Temple of Ofcol")
       '("dwarf" "Entrance to Mountain")
       '("demonspace" "The Chamber")
       '("inken" "On a hill")
       '("melissa" "The northern Shopping Hall")
       '("sara" "On a drawbridge")
       '("sodom" "Skull Gate")
       '("purple" "Climbing the rock")
       '("rome" "The Temple of Rome")
       '("draconia" "A Lovely Beach")
       '("elven_palace" "The Elven Bow Shop")
       '("vamp" "On the drawbridge")
       ))

(setq emuds-speedwalk
      (list
       '("alkhan" "dokhan" ".47nw8n") ; ok
       '("alkhan" "moonglow" ".47nw9n5es2we2ses2ene3n2wn") ; ok
       '("alkhan" "riva" ".47nw8n5n4wss8w2n") ; ok
       '("alkhan" "saru" ".47nw9nw4s3w8nenw") ; ok
       '("atalia" "fanhir" ".swn16w5n8w4n5wu3nwn")
       '("atalia" "inken" ".swn5w4s4e4s" "open gate" ".6suse2swsusu2susu2swdw2s2ed5eue")
       '("atalia" "midgaard" ".swn16w3nenen2e2n11e4n3w2n")
       '("atalia" "mitra" ".swn17w12n7w3sw3n")
       '("atalia" "moonglow" ".swn16w3s6w2nwn")
       '("atalia" "purple" ".swn5w4s4e4s" "open gate" ".5s3ws3w3su3sde3su")
       '("atalia" "riva" ".swn20wnw3n7w2s5w2s8w2n")
       '("atalia" "rome" ".sen9e" "open gate" ".6enes6en2es")
       '("atalia" "weramak" ".swn5w4s4e10suses2e3n")
       '("black_harbour" "fanhir" ".w3s7wnwsw2nws5w2s6w3swn")
       '("demonlord" "kerofk" ".swuwwueneuuuuuuu" "open trapdoor" ".u7wnes6ennes")
       '("rand" "kerofk" ".7wnes6ennes")
       '("dokhan" "saru" ".nw4s3w8nenw")
       '("dokhan" "alkhan" ".8se47s")
       '("dokhan" "moonglow" ".n5es2we2ses2ene3n2wn")
       '("dokhan" "riva" ".n5n4wss8w2n")
;;;    '("draconia" "moonglow" ".swnw4n3wn")
       '("dwarf" "kerofk" ".e4ses6e2nes")
       '("fanhir" "black_harbour" ".se3n6e2n5ene2senes7e3ne")
       '("fanhir" "mitra" ".se3n6e2n5ene2senes6e3n")
       '("fanhir" "midgaard" ".s4e4swes4en2esn8es9e2n2w3n")
       '("fanhir" "riva" ".s4e4sw3sw2sws5w2s8w2n")
;;;    '("fanhir" "wuss"  ".se3sd3es3wn 2wn3e6s d2s3w2un")
       '("fanhir" "troll" ".se3sd3es3wn 4e2n7e2sd2s3w2un")
       '("hercules" "snowman" ".ennnwnnnww")
       '("hercules" "winddancer" ".nee")
       '("saru" "dokha" ".essw4s3ene3nees")
       '("saru" "midgaard" ".e3sn2we4s3ene6n2e3n5en6en16e2n2w3n")
       '("saru" "moonglow" ".e2sw4s13ene3n2wn")
       '("saru" "riva" ".e2sw4s3ene6n2en4w2s8w2n")
       '("inken" "melissa" ".swde7s2w")
       '("inken" "sara" ".wd5wewuwwnneuenndndnndndnennwndn3ws3w3su3sde3snsu3swwdwwsww3swwew3s3enn5wnnsswnw" )
       '("inken" "sodom" ".wd5wuwsususwdsdw2ds2e3sw3sw")
       '("inken" "tittytwister" ".swdes3wnw3s2e3s2w2n3w")
       '("inken" "vamp" ".swde7s2w4s" ".3enws3e")
       '("kerofk" "demonlord" ".nwss6wnws7e" "open trapdoor" ".dddddddddws" "open door" ".wdeede")
       '("kerofk" "rand" ".nwss6wnws7e")
       '("kerofk" "dwarf" ".nw2s6wnw4nw")
       '("kerofk" "moonglow" ".nwss4w9s3w4sees3e6s3en")
       '("kerofk" "ofcol" ".nwss4w9se2n9e")
       '("merkle" "black_harbour" ".4se3se2s2ese3s7e3ne")
       '("merkle" "fanhir"        ".4se3se2s2ese2swsw2nws5w2s6w3swn")
       '("merkle" "wuss" ".n2w4n5w2un")
;;;    '("midgaard" "demonspace" ".2s20e2u2w2u2eu4w")
       '("midgaard" "demonspace" ".2s19e2u2w2u2eu4w")
       '("midgaard" "fanhir" ".3s2e2s5we5wn2wn18wu3nwn")
       '("midgaard" "grassy" ".3s2e2s12e4n3w")
       '("midgaard" "saru" ".4sn2e2s11w2s2wswsw7s2wsws14w8nenw")
       '("midgaard" "lemuria" ".3s2e2s11w2s2wsws3w5d")
       '("midgaard" "moonglow" "withdraw 150" ".2s4en" "buy blue" ".s4w3neu" "pat blue" ".d2n3en" )
       '("midgaard" "ofcol" ".3s2e2s11w2s2wswsws5wsn7w4s7e")
       '("midgaard" "riva" ".3s2e2s12w2sws12w2s7w2s8w2n")
       '("midgaard" "shire" ".2s3wuwd12w6n3en")
       '("mitra" "atalia" ".3se3n7e12s16esen")
;;;    '("mitra" "fanhir" ".3s6wnwsw2nws5w2s6w3swn")
       '("mitra" "fanhir" ".3se3n2e2s3w3n7wn")
       '("mitra" "ianianto" ".3se3n2e18s12w8nenw")
       '("mitra" "isle_of_trees" ".3se3n2e4swsn12wne")
       '("mitra" "midgaard" ".3se3n7es3e2ses2es9e2n2wnwe2n")
       '("mitra" "moonglow" ".3se3n2e14s2wn")
       '("mitra" "ofcol" ".3se3n2e10s7w4s7e")
       '("moonglow" "alisia" ".s3w6nws4ws2ws")
       '("moonglow" "alkhan" ".s2e4s3wnw3n4w9se47s")
       '("moonglow" "assasin" ".s3w6nws9wn")
       '("moonglow" "bolg" ".s3w9n4wnwn2wn2w4nw7n2wnwuenwne3ne")
       '("moonglow" "castle_dragon" ".s2e5s13wn13w3nw3nw10nw6n")
       '("moonglow" "dokhan" ".s2e4s3wnw3n4ws")
       '("moonglow" "draconia" ".s3e4sesen")
       '("moonglow" "elven_palace" ".s2e2n3wne3n4e2n4w2n")
       '("moonglow" "fanhir" ".s2e10nwn2w6wunnnwn")
       '("moonglow" "herkules" ".s2e10n7wn2w2ne")
       '("moonglow" "saru" ".s2ewe4s12w8nenw")
       '("moonglow" "kerofk" ".swww6n3wnww4n3e9n4ennes")
       '("moonglow" "lemuria" ".s2e5n3e5d")
       '("moonglow" "looran" ".s3w6nws9wn")
       '("moonglow" "midgaard" ".s7e5nenen2e2n11e4n3w2n")
       '("moonglow" "ofcol" ".swww9nene8n7e")
       '("moonglow" "rainbow_warrior" ".s2e4s3wnw3n2w")
       '("moonglow" "riva" ".s2e6n5w2s7w2s8w2")
       '("ofcol" "kerofk" ".9w2sw9n4ennes") ; ok
       '("ofcol" "midgaard" ".7w4n7e3n4en16e2n2w3n")
       '("ofcol" "moonglow" ".7w8swsw9s3en")
       '("ofcol" "riva" ".7w4n7e2n5w2s7w2s8w2n")
       '("raff" "troll" ".3es3wn4e2n7e2sd2s3w2un")
       '("raff" "mitra" ".u6n6e2n5ene2senes6e3n")
       '("riva" "alkhan" ".2s8enn4e5s8se47s")
       '("riva" "brim" ".2s5w2nw6n2e")
       '("riva" "saru" ".2s8e2n3e4sw4s3w8nenw")
       '("riva" "midgaard" ".2s8e2n4e2n5en6en16e2n2w3n")
       '("riva" "moonglow" ".2s8e2n4e2n8e6s2wn")
       '("riva" "obelisk" ".2s5wn2wu3wsw2sws2dnw2n2w")
       '("riva" "ofcol" ".2s8e2n4e2n9e2s8w4s7e")
       '("riva" "thieves" ".2s5wn2w3s4wswswn")
       '("sara" "inken" ".eenneeeeesswwwnnneweennneeneeueennndnsnnnwunnndnnneeeneeesusesswsusussususswdwsseedeweeeeeue" )
       '("shire" "midgaard" ".s3w6s12e" "climb rope" ".d3e2n")
       '("sodom" "inken" ".e3ne3n2wn2ueunuendndned5eue")
       '("wuss" "merkle" ".s2d5e4s2es")
       )
      )
